=head1 Software development

The Xinutec community develops open source software used to provide services to
its members and guests. We maintain a fork of the Internet Relay Chat server
L<InspIRCd|http://www.inspircd.org/> in our git repository at
L<GitHub|https://github.com/xinutec/inspircd>. In addition, we forked the
L<Irssi|http://irssi.org/> IRC client, which we also maintain in a repository at
L<GitHub|https://github.com/xinutec/irssi>.

We forked InspIRCd so that we can easily implement additional features we deem
useful for our network. Our Irssi fork happened because of the unfortunate lack
of upstream activity. We maintain, correct and extend this console IRC client
for a cleaner Perl interface and better Unicode handling.

If you want to contribute to our software, it is as simple as sending a GitHub
pull request, sending an email or talking to one of our staff members to tell us
where your git repository is at.

Most of our joint software development efforts, including the two forked
projects, do not require a Contributor License Agreement to be signed. For the
few that do require one, you may refer to the L<contributing> page for further
information.
